version: "3.0"
services:
  mariadb:
    container_name: test_db_mariadb
    image: mariadb:11.2.4
    ports:
      - "8080:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DATABASE=test_db
